/**
 * This class is generated by jOOQ
 */
package lv.whattobuy.domain;

/**
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.databasechangelog
	 */
	public static final lv.whattobuy.domain.tables.Databasechangelog DATABASECHANGELOG = lv.whattobuy.domain.tables.Databasechangelog.DATABASECHANGELOG;

	/**
	 * The table public.databasechangeloglock
	 */
	public static final lv.whattobuy.domain.tables.Databasechangeloglock DATABASECHANGELOGLOCK = lv.whattobuy.domain.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

	/**
	 * The table public.item
	 */
	public static final lv.whattobuy.domain.tables.Item ITEM = lv.whattobuy.domain.tables.Item.ITEM;

	/**
	 * The table public.user
	 */
	public static final lv.whattobuy.domain.tables.User USER = lv.whattobuy.domain.tables.User.USER;

	/**
	 * The table public.user_roles
	 */
	public static final lv.whattobuy.domain.tables.UserRoles USER_ROLES = lv.whattobuy.domain.tables.UserRoles.USER_ROLES;

	/**
	 * The table public.users
	 */
	public static final lv.whattobuy.domain.tables.Users USERS = lv.whattobuy.domain.tables.Users.USERS;
}
