/**
 * This class is generated by jOOQ
 */
package lv.whattobuy.domain.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Databasechangeloglock extends org.jooq.impl.TableImpl<lv.whattobuy.domain.tables.records.DatabasechangeloglockRecord> {

	private static final long serialVersionUID = -1178196195;

	/**
	 * The reference instance of <code>public.databasechangeloglock</code>
	 */
	public static final lv.whattobuy.domain.tables.Databasechangeloglock DATABASECHANGELOGLOCK = new lv.whattobuy.domain.tables.Databasechangeloglock();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lv.whattobuy.domain.tables.records.DatabasechangeloglockRecord> getRecordType() {
		return lv.whattobuy.domain.tables.records.DatabasechangeloglockRecord.class;
	}

	/**
	 * The column <code>public.databasechangeloglock.id</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.DatabasechangeloglockRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.databasechangeloglock.locked</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.DatabasechangeloglockRecord, java.lang.Boolean> LOCKED = createField("locked", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

	/**
	 * The column <code>public.databasechangeloglock.lockgranted</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.DatabasechangeloglockRecord, java.sql.Timestamp> LOCKGRANTED = createField("lockgranted", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.databasechangeloglock.lockedby</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.DatabasechangeloglockRecord, java.lang.String> LOCKEDBY = createField("lockedby", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>public.databasechangeloglock</code> table reference
	 */
	public Databasechangeloglock() {
		this("databasechangeloglock", null);
	}

	/**
	 * Create an aliased <code>public.databasechangeloglock</code> table reference
	 */
	public Databasechangeloglock(java.lang.String alias) {
		this(alias, lv.whattobuy.domain.tables.Databasechangeloglock.DATABASECHANGELOGLOCK);
	}

	private Databasechangeloglock(java.lang.String alias, org.jooq.Table<lv.whattobuy.domain.tables.records.DatabasechangeloglockRecord> aliased) {
		this(alias, aliased, null);
	}

	private Databasechangeloglock(java.lang.String alias, org.jooq.Table<lv.whattobuy.domain.tables.records.DatabasechangeloglockRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lv.whattobuy.domain.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lv.whattobuy.domain.tables.records.DatabasechangeloglockRecord> getPrimaryKey() {
		return lv.whattobuy.domain.Keys.PK_DATABASECHANGELOGLOCK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lv.whattobuy.domain.tables.records.DatabasechangeloglockRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lv.whattobuy.domain.tables.records.DatabasechangeloglockRecord>>asList(lv.whattobuy.domain.Keys.PK_DATABASECHANGELOGLOCK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lv.whattobuy.domain.tables.Databasechangeloglock as(java.lang.String alias) {
		return new lv.whattobuy.domain.tables.Databasechangeloglock(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lv.whattobuy.domain.tables.Databasechangeloglock rename(java.lang.String name) {
		return new lv.whattobuy.domain.tables.Databasechangeloglock(name, null);
	}
}
