/**
 * This class is generated by jOOQ
 */
package lv.whattobuy.domain.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Item extends org.jooq.impl.TableImpl<lv.whattobuy.domain.tables.records.ItemRecord> {

	private static final long serialVersionUID = 2108075958;

	/**
	 * The reference instance of <code>public.item</code>
	 */
	public static final lv.whattobuy.domain.tables.Item ITEM = new lv.whattobuy.domain.tables.Item();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lv.whattobuy.domain.tables.records.ItemRecord> getRecordType() {
		return lv.whattobuy.domain.tables.records.ItemRecord.class;
	}

	/**
	 * The column <code>public.item.id</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.ItemRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.item.name</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.ItemRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.item.status</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.ItemRecord, java.lang.Boolean> STATUS = createField("status", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>public.item.user_id</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.ItemRecord, java.lang.Long> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.item</code> table reference
	 */
	public Item() {
		this("item", null);
	}

	/**
	 * Create an aliased <code>public.item</code> table reference
	 */
	public Item(java.lang.String alias) {
		this(alias, lv.whattobuy.domain.tables.Item.ITEM);
	}

	private Item(java.lang.String alias, org.jooq.Table<lv.whattobuy.domain.tables.records.ItemRecord> aliased) {
		this(alias, aliased, null);
	}

	private Item(java.lang.String alias, org.jooq.Table<lv.whattobuy.domain.tables.records.ItemRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lv.whattobuy.domain.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lv.whattobuy.domain.tables.records.ItemRecord, java.lang.Long> getIdentity() {
		return lv.whattobuy.domain.Keys.IDENTITY_ITEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lv.whattobuy.domain.tables.records.ItemRecord> getPrimaryKey() {
		return lv.whattobuy.domain.Keys.PKEY_ITEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lv.whattobuy.domain.tables.records.ItemRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lv.whattobuy.domain.tables.records.ItemRecord>>asList(lv.whattobuy.domain.Keys.PKEY_ITEM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<lv.whattobuy.domain.tables.records.ItemRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<lv.whattobuy.domain.tables.records.ItemRecord, ?>>asList(lv.whattobuy.domain.Keys.ITEM__FK_USER_ITEM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lv.whattobuy.domain.tables.Item as(java.lang.String alias) {
		return new lv.whattobuy.domain.tables.Item(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lv.whattobuy.domain.tables.Item rename(java.lang.String name) {
		return new lv.whattobuy.domain.tables.Item(name, null);
	}
}
