/**
 * This class is generated by jOOQ
 */
package lv.whattobuy.domain.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends org.jooq.impl.TableImpl<lv.whattobuy.domain.tables.records.UserRecord> {

	private static final long serialVersionUID = -520119348;

	/**
	 * The reference instance of <code>public.user</code>
	 */
	public static final lv.whattobuy.domain.tables.User USER = new lv.whattobuy.domain.tables.User();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lv.whattobuy.domain.tables.records.UserRecord> getRecordType() {
		return lv.whattobuy.domain.tables.records.UserRecord.class;
	}

	/**
	 * The column <code>public.user.id</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.UserRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.user.name</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.UserRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.user.username</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.UserRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.user.password</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.UserRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.user.enabled</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.UserRecord, java.lang.Boolean> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * Create a <code>public.user</code> table reference
	 */
	public User() {
		this("user", null);
	}

	/**
	 * Create an aliased <code>public.user</code> table reference
	 */
	public User(java.lang.String alias) {
		this(alias, lv.whattobuy.domain.tables.User.USER);
	}

	private User(java.lang.String alias, org.jooq.Table<lv.whattobuy.domain.tables.records.UserRecord> aliased) {
		this(alias, aliased, null);
	}

	private User(java.lang.String alias, org.jooq.Table<lv.whattobuy.domain.tables.records.UserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lv.whattobuy.domain.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lv.whattobuy.domain.tables.records.UserRecord, java.lang.Long> getIdentity() {
		return lv.whattobuy.domain.Keys.IDENTITY_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lv.whattobuy.domain.tables.records.UserRecord> getPrimaryKey() {
		return lv.whattobuy.domain.Keys.PKEY_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lv.whattobuy.domain.tables.records.UserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lv.whattobuy.domain.tables.records.UserRecord>>asList(lv.whattobuy.domain.Keys.PKEY_USER);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lv.whattobuy.domain.tables.User as(java.lang.String alias) {
		return new lv.whattobuy.domain.tables.User(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lv.whattobuy.domain.tables.User rename(java.lang.String name) {
		return new lv.whattobuy.domain.tables.User(name, null);
	}
}
