/**
 * This class is generated by jOOQ
 */
package lv.whattobuy.domain.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoles extends org.jooq.impl.TableImpl<lv.whattobuy.domain.tables.records.UserRolesRecord> {

	private static final long serialVersionUID = 1199180474;

	/**
	 * The reference instance of <code>public.user_roles</code>
	 */
	public static final lv.whattobuy.domain.tables.UserRoles USER_ROLES = new lv.whattobuy.domain.tables.UserRoles();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lv.whattobuy.domain.tables.records.UserRolesRecord> getRecordType() {
		return lv.whattobuy.domain.tables.records.UserRolesRecord.class;
	}

	/**
	 * The column <code>public.user_roles.id</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.UserRolesRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.user_roles.username</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.UserRolesRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.user_roles.role</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.UserRolesRecord, java.lang.String> ROLE = createField("role", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>public.user_roles</code> table reference
	 */
	public UserRoles() {
		this("user_roles", null);
	}

	/**
	 * Create an aliased <code>public.user_roles</code> table reference
	 */
	public UserRoles(java.lang.String alias) {
		this(alias, lv.whattobuy.domain.tables.UserRoles.USER_ROLES);
	}

	private UserRoles(java.lang.String alias, org.jooq.Table<lv.whattobuy.domain.tables.records.UserRolesRecord> aliased) {
		this(alias, aliased, null);
	}

	private UserRoles(java.lang.String alias, org.jooq.Table<lv.whattobuy.domain.tables.records.UserRolesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lv.whattobuy.domain.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lv.whattobuy.domain.tables.records.UserRolesRecord, java.lang.Long> getIdentity() {
		return lv.whattobuy.domain.Keys.IDENTITY_USER_ROLES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lv.whattobuy.domain.tables.records.UserRolesRecord> getPrimaryKey() {
		return lv.whattobuy.domain.Keys.PKEY_USER_ROLES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lv.whattobuy.domain.tables.records.UserRolesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lv.whattobuy.domain.tables.records.UserRolesRecord>>asList(lv.whattobuy.domain.Keys.PKEY_USER_ROLES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lv.whattobuy.domain.tables.UserRoles as(java.lang.String alias) {
		return new lv.whattobuy.domain.tables.UserRoles(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lv.whattobuy.domain.tables.UserRoles rename(java.lang.String name) {
		return new lv.whattobuy.domain.tables.UserRoles(name, null);
	}
}
