/**
 * This class is generated by jOOQ
 */
package lv.whattobuy.domain.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends org.jooq.impl.TableImpl<lv.whattobuy.domain.tables.records.UsersRecord> {

	private static final long serialVersionUID = -133138218;

	/**
	 * The reference instance of <code>public.users</code>
	 */
	public static final lv.whattobuy.domain.tables.Users USERS = new lv.whattobuy.domain.tables.Users();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lv.whattobuy.domain.tables.records.UsersRecord> getRecordType() {
		return lv.whattobuy.domain.tables.records.UsersRecord.class;
	}

	/**
	 * The column <code>public.users.id</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.UsersRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.users.name</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.UsersRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.users.username</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.UsersRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.users.password</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.UsersRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.users.enabled</code>.
	 */
	public final org.jooq.TableField<lv.whattobuy.domain.tables.records.UsersRecord, java.lang.Boolean> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * Create a <code>public.users</code> table reference
	 */
	public Users() {
		this("users", null);
	}

	/**
	 * Create an aliased <code>public.users</code> table reference
	 */
	public Users(java.lang.String alias) {
		this(alias, lv.whattobuy.domain.tables.Users.USERS);
	}

	private Users(java.lang.String alias, org.jooq.Table<lv.whattobuy.domain.tables.records.UsersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Users(java.lang.String alias, org.jooq.Table<lv.whattobuy.domain.tables.records.UsersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lv.whattobuy.domain.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lv.whattobuy.domain.tables.Users as(java.lang.String alias) {
		return new lv.whattobuy.domain.tables.Users(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lv.whattobuy.domain.tables.Users rename(java.lang.String name) {
		return new lv.whattobuy.domain.tables.Users(name, null);
	}
}
