/**
 * This class is generated by jOOQ
 */
package lv.whattobuy.domain.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemRecord extends org.jooq.impl.UpdatableRecordImpl<lv.whattobuy.domain.tables.records.ItemRecord> implements org.jooq.Record4<java.lang.Long, java.lang.String, java.lang.Boolean, java.lang.Long> {

	private static final long serialVersionUID = -46653664;

	/**
	 * Setter for <code>public.item.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.item.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.item.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.item.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.item.status</code>.
	 */
	public void setStatus(java.lang.Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.item.status</code>.
	 */
	public java.lang.Boolean getStatus() {
		return (java.lang.Boolean) getValue(2);
	}

	/**
	 * Setter for <code>public.item.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.item.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.String, java.lang.Boolean, java.lang.Long> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Long, java.lang.String, java.lang.Boolean, java.lang.Long> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return lv.whattobuy.domain.tables.Item.ITEM.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return lv.whattobuy.domain.tables.Item.ITEM.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field3() {
		return lv.whattobuy.domain.tables.Item.ITEM.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return lv.whattobuy.domain.tables.Item.ITEM.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value3() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value3(java.lang.Boolean value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord value4(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemRecord values(java.lang.Long value1, java.lang.String value2, java.lang.Boolean value3, java.lang.Long value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ItemRecord
	 */
	public ItemRecord() {
		super(lv.whattobuy.domain.tables.Item.ITEM);
	}

	/**
	 * Create a detached, initialised ItemRecord
	 */
	public ItemRecord(java.lang.Long id, java.lang.String name, java.lang.Boolean status, java.lang.Long userId) {
		super(lv.whattobuy.domain.tables.Item.ITEM);

		setValue(0, id);
		setValue(1, name);
		setValue(2, status);
		setValue(3, userId);
	}
}
